'use strict';

const { getDb, logAudit } = require('../db/init');
const path = require('path');
const fs = require('fs');

function publishRoutes(db) {
  const express = require('express');
  const router = express.Router();
  const { requireAdmin } = require('./auth');

  router.post('/publish/products', requireAdmin, (req, res) => {
    try {
      const categories = db.prepare('SELECT * FROM product_categories WHERE is_active = 1 ORDER BY sort_order ASC, id ASC').all();
      const allProducts = db.prepare(
        'SELECT p.*, c.slug as category_slug, c.i18n_key as category_i18n_key FROM products p LEFT JOIN product_categories c ON p.category_id = c.id WHERE p.is_active = 1 ORDER BY p.sort_order ASC, p.id ASC'
      ).all();
      const allImages = db.prepare('SELECT * FROM product_images ORDER BY sort_order ASC').all();

      // Group images by product_id
      const imgMap = {};
      allImages.forEach(img => {
        if (!imgMap[img.product_id]) imgMap[img.product_id] = [];
        imgMap[img.product_id].push(img);
      });

      // Group products by category
      const catMap = {};
      allProducts.forEach(p => {
        const catId = p.category_id || 0;
        const catSlug = p.category_slug || 'Uncategorized';
        if (!catMap[catSlug]) {
          catMap[catSlug] = { category: p.category_i18n_key || p.category_slug, products: [] };
        }
        catMap[catSlug].products.push({
          category: p.category_i18n_key || p.category_slug,
          subCategory: p.sub_category || null,
          model: p.model,
          status: p.status,
          is_active: p.is_active ? true : false,
          badge: p.badge || null,
          badgeColor: p.badge_color || null,
          power: p.power || null,
          throughput: p.throughput || null,
          averageTime: p.average_time || null,
          voltage: p.voltage || null,
          frequency: p.frequency || null,
          material: p.material || null,
          productDimensions: p.product_dimensions || null,
          color: p.color || null,
          controlMethod: p.control_method || null,
          launchTime: p.launch_time || null,
          images: (imgMap[p.id] || []).map(i => ({
            filePath: i.file_path,
            isPrimary: !!i.is_primary,
            sortOrder: i.sort_order
          }))
        });
      });

      const table = [];
      // First add categories that have products
      const usedCats = new Set(Object.keys(catMap));
      categories.forEach(cat => {
        if (catMap[cat.slug]) {
          table.push(catMap[cat.slug]);
        }
      });
      // Then add any remaining
      Object.keys(catMap).forEach(slug => {
        if (!usedCats.has(slug) || !categories.find(c => c.slug === slug)) {
          table.push(catMap[slug]);
        }
      });

      // Generate JS file
      const output = `// product-data-table.js — Auto-generated by CMS (${new Date().toISOString()})\n// DO NOT EDIT MANUALLY — Changes will be overwritten on next publish\n\nexport const PRODUCT_DATA_TABLE = ${JSON.stringify(table, null, 2)};\n`;

      const targetPath = path.join(__dirname, '..', '..', '..', 'src', 'assets', 'js', 'product-data-table.js');
      fs.writeFileSync(targetPath, output, 'utf-8');

      logAudit(db, req.user.userId, req.user.username, 'publish', 'products', null, null, {
        categories: categories.length,
        products: allProducts.length,
        images: allImages.length
      });

      res.json({
        message: 'Published successfully',
        stats: { categories: categories.length, products: allProducts.length, images: allImages.length }
      });
    } catch (e) {
      res.status(500).json({ error: e.message });
    }
  });

  return router;
}

module.exports = { publishRoutes };
