'use strict';

const { getDb, logAudit } = require('../db/init');
const path = require('path');
const fs = require('fs');

function publishRoutes(db) {
  const express = require('express');
  const router = express.Router();
  const { requireAdmin } = require('./auth');

  router.post('/publish/products', requireAdmin, (req, res) => {
    try {
      const categories = db.prepare('SELECT * FROM product_categories WHERE is_active = 1 ORDER BY sort_order ASC, id ASC').all();
      const allProducts = db.prepare(
        'SELECT p.*, c.slug as category_slug, c.i18n_key as category_i18n_key FROM products p LEFT JOIN product_categories c ON p.category_id = c.id WHERE p.is_active = 1 ORDER BY p.sort_order ASC, p.id ASC'
      ).all();
      const allImages = db.prepare('SELECT * FROM product_images ORDER BY sort_order ASC').all();

      // Group images by product_id
      const imgMap = {};
      allImages.forEach(img => {
        if (!imgMap[img.product_id]) imgMap[img.product_id] = [];
        imgMap[img.product_id].push(img);
      });

      // Group products by category
      const catMap = {};
      allProducts.forEach(p => {
        const catId = p.category_id || 0;
        const catSlug = p.category_slug || 'Uncategorized';
        if (!catMap[catSlug]) {
          catMap[catSlug] = { category: p.category_i18n_key || p.category_slug, products: [] };
        }
        catMap[catSlug].products.push({
          category: p.category_i18n_key || p.category_slug,
          subCategory: p.sub_category || null,
          model: p.model,
          status: p.status,
          is_active: p.is_active ? true : false,
          badge: p.badge || null,
          badgeColor: p.badge_color || null,
          power: p.power || null,
          throughput: p.throughput || null,
          averageTime: p.average_time || null,
          voltage: p.voltage || null,
          frequency: p.frequency || null,
          material: p.material || null,
          productDimensions: p.product_dimensions || null,
          color: p.color || null,
          controlMethod: p.control_method || null,
          launchTime: p.launch_time || null,
          images: (imgMap[p.id] || []).map(i => ({
            filePath: i.file_path,
            isPrimary: !!i.is_primary,
            sortOrder: i.sort_order
          }))
        });
      });

      const table = [];
      // First add categories that have products
      const usedCats = new Set(Object.keys(catMap));
      categories.forEach(cat => {
        if (catMap[cat.slug]) {
          table.push(catMap[cat.slug]);
        }
      });
      // Then add any remaining
      Object.keys(catMap).forEach(slug => {
        if (!usedCats.has(slug) || !categories.find(c => c.slug === slug)) {
          table.push(catMap[slug]);
        }
      });

      // Generate JS file
      const output = `// product-data-table.js — Auto-generated by CMS (${new Date().toISOString()})\n// DO NOT EDIT MANUALLY — Changes will be overwritten on next publish\n\nwindow.PRODUCT_DATA_TABLE = ${JSON.stringify(table, null, 2)};\n`;

      const targetPath = path.join(__dirname, '..', '..', '..', 'src', 'assets', 'js', 'product-data-table.js');
      fs.writeFileSync(targetPath, output, 'utf-8');

      logAudit(db, req.user.userId, req.user.username, 'publish', 'products', null, null, {
        categories: categories.length,
        products: allProducts.length,
        images: allImages.length
      });

      res.json({
        message: 'Published successfully',
        stats: { categories: categories.length, products: allProducts.length, images: allImages.length }
      });
    } catch (e) {
      res.status(500).json({ error: e.message });
    }
  });

  // ── Markdown → HTML ──────────────────────────────────────────
  function mdToHtml(md) {
    if (!md) return '';
    return md
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>')
      .replace(/^!\[(.+?)\]\((.+?)\)$/gm, '<img src="$2" alt="$1" class="w-full rounded-lg my-4">')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>')
      .replace(/^/, '<p>').replace(/$/, '</p>');
  }

  // ── Detail page templates (based on existing detail-*.html) ──
  function detailPcHtml(post) {
    const bodyHtml = mdToHtml(post.content_markdown);
    const escTitle = (post.title || '').replace(/"/g, '&quot;');
    const escExcerpt = (post.excerpt || '').replace(/"/g, '&quot;');
    return `<!DOCTYPE html>
<html class="light" lang="zh-CN">
<head>
<meta charset="utf-8"/>
<link rel="canonical" href="/news/${post.slug}/" />
<meta name="description" content="${escExcerpt || escTitle}">
<meta property="og:type" content="article">
<meta property="og:title" content="YuKoLi 智能厨具 | ${escTitle}">
<meta property="og:description" content="${escExcerpt || escTitle}">
<meta property="og:url" content="https://www.kitchen.yukoli.com/news/${post.slug}/">
<meta property="og:image" content="https://www.kitchen.yukoli.com/assets/images/og-home.webp">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>YuKoLi 智能厨具 | ${escTitle}</title>
<link rel="preload" href="/assets/fonts/local-fonts.css" as="style">
<link rel="preload" href="/assets/css/styles.css" as="style">
<link rel="preload" href="/assets/css/tailwind.css" as="style">
<link rel="preload" href="/assets/fonts/public-sans-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/public-sans-latin-700-normal.woff2" as="font" type="font/woff2" crossorigin>
<link href="/assets/fonts/local-fonts.css" rel="stylesheet"/>
<link rel="stylesheet" href="/assets/css/styles.css">
<link rel="stylesheet" href="/assets/css/tailwind.css">
<link rel="stylesheet" href="/assets/css/z-index-system.css">
<link rel="stylesheet" href="/assets/css/performance-optimizations.css"/>
<style>
  body { font-family: 'Public Sans', sans-serif; }
  .article-body p { margin-bottom: 1.25em; line-height: 1.8; }
  .article-body h2 { margin-top: 2em; margin-bottom: 0.75em; }
</style>
<!-- Dark mode: apply saved preference before first paint (prevents flash) -->
<script>(function(){if(localStorage.getItem('darkMode')==='true')document.documentElement.classList.add('dark')})()</script>
<link rel="stylesheet" href="/assets/css/skeleton.css"/>
<link rel="icon" href="/assets/images/logo_header.webp" type="image/webp">
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "${escTitle}",
  "description": "${escExcerpt || escTitle}",
  "datePublished": "${post.published_at || ''}",
  "publisher": {
    "@type": "Organization",
    "name": "YuKoLi 跃迁力科技",
    "url": "https://www.kitchen.yukoli.com"
  },
  "isPartOf": {
    "@type": "WebSite",
    "name": "YuKoLi 智能厨具",
    "url": "https://www.kitchen.yukoli.com"
  }
}
</script>
</head>
<body class="bg-background-light dark:bg-background-dark text-slate-900 dark:text-slate-100 antialiased overflow-x-hidden">
<div class="relative flex h-auto min-h-screen w-full flex-col">

<!-- Top Navigation Bar -->
<navigator data-component="navigator"
  data-variant="pc"
  data-active="news"
  data-cta-text-key="nav_get_quote"
  data-cta-href="/quote"></navigator>

<main id="spa-content" class="flex-1">

<!-- Article Section -->
<section class="py-16 md:py-24">
<div class="px-6 md:px-10 lg:px-16 xl:px-20 max-w-4xl mx-auto">

  <!-- Breadcrumb / Back -->
  <a href="/news/" class="inline-flex items-center gap-1 text-primary font-semibold text-sm mb-8 hover:gap-2 transition-all">
    <span class="material-symbols-outlined text-base">arrow_back</span>
    <span>返回新闻列表</span>
  </a>

  <!-- Article Header -->
  <header class="mb-10">
    <div class="flex items-center gap-3 mb-4">
      <span class="inline-flex items-center px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-widest">
        ${post.category === 'case' ? '客户案例' : '新闻资讯'}
      </span>
      <time class="text-sm text-slate-500 dark:text-slate-400 font-medium">
        发布于 ${(post.published_at || '').slice(0, 10)}
      </time>
    </div>
    <h1 class="text-4xl md:text-5xl font-black leading-tight tracking-tight">${post.title}</h1>
  </header>

  <!-- Article Body -->
  <article class="article-body text-lg text-slate-700 dark:text-slate-300 leading-relaxed">
  ${bodyHtml}
  </article>

  <!-- Share & Actions -->
  <div class="mt-12 pt-8 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between">
    <a href="/news/" class="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-white font-semibold text-sm hover:bg-primary/90 transition-colors shadow-sm">
      <span class="material-symbols-outlined text-base">arrow_back</span>
      返回新闻列表
    </a>
    <button class="inline-flex items-center gap-2 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 font-medium text-sm hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
      <span class="material-symbols-outlined text-base">share</span>
      分享
    </button>
  </div>

</div>
</section>

</main>

</div>

    <script src="/assets/js/ui/dropdown-styles.js"></script>
<script defer src="/assets/js/ui/products-dropdown.js?v=20260322-v3"></script>
<script defer src="/assets/js/nav-config.js?v=20260415"></script>
    <script defer src="/assets/js/ui/navigator.js?v=20260322-v3"></script>
<script defer src="/assets/js/ui/search-engine.js"></script>
<script defer src="/assets/js/ui/footer.js?v=20260322-v3"></script>
<script defer src="/assets/js/lang-registry.js"></script>
<script defer src="/assets/js/translations.js"></script>
<script defer src="/assets/js/translations-dropdown-template.js"></script>
<script defer src="/assets/js/contacts.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    if (window.translationManager) window.translationManager.initialize();
  });
</script>

<script src="/assets/js/utils/device-utils.js"></script>
<script src="/assets/js/spa-router.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    if (window.SpaRouter && typeof window.SpaRouter.init === 'function') {
      window.SpaRouter.init();
    }
  });
</script>
</body>
</html>`;
  }

  function detailTabletHtml(post) {
    const bodyHtml = mdToHtml(post.content_markdown);
    const escTitle = (post.title || '').replace(/"/g, '&quot;');
    const escExcerpt = (post.excerpt || '').replace(/"/g, '&quot;');
    return `<!DOCTYPE html>
<html class="light" lang="zh-CN">
<head>
<meta charset="utf-8"/>
<link rel="canonical" href="/news/${post.slug}/" />
<meta name="description" content="${escExcerpt || escTitle}">
<meta property="og:type" content="article">
<meta property="og:title" content="YuKoLi 智能厨具 | ${escTitle}">
<meta property="og:description" content="${escExcerpt || escTitle}">
<meta property="og:url" content="https://www.kitchen.yukoli.com/news/${post.slug}/">
<meta property="og:image" content="https://www.kitchen.yukoli.com/assets/images/og-home.webp">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>YuKoLi 智能厨具 | ${escTitle}</title>
<link rel="preload" href="/assets/fonts/local-fonts.css" as="style">
<link rel="preload" href="/assets/css/styles.css" as="style">
<link rel="preload" href="/assets/css/tailwind.css" as="style">
<link rel="preload" href="/assets/fonts/public-sans-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/public-sans-latin-700-normal.woff2" as="font" type="font/woff2" crossorigin>
<link href="/assets/fonts/local-fonts.css" rel="stylesheet"/>
<link rel="stylesheet" href="/assets/css/styles.css">
<link rel="stylesheet" href="/assets/css/tailwind.css">
<link rel="stylesheet" href="/assets/css/z-index-system.css">
<link rel="stylesheet" href="/assets/css/performance-optimizations.css"/>
<style>
  .article-body p { margin-bottom: 1.25em; line-height: 1.8; }
</style>
<!-- Dark mode: apply saved preference before first paint (prevents flash) -->
<script>(function(){if(localStorage.getItem('darkMode')==='true')document.documentElement.classList.add('dark')})()</script>
<link rel="stylesheet" href="/assets/css/skeleton.css"/>
<link rel="icon" href="/assets/images/logo_header.webp" type="image/webp">
</head>
<body class="bg-background-light dark:bg-background-dark font-display text-slate-900 dark:text-slate-100 antialiased overflow-x-hidden">
<div class="relative flex min-h-screen flex-col">

<!-- Navigator -->
<navigator data-component="navigator"
  data-variant="tablet"
  data-search="true"
  data-active="news"
  data-cta-text-key="nav_get_quote"
  data-cta-href="/quote"></navigator>

<!-- Main Content -->
<main id="spa-content" class="flex-1 max-w-4xl mx-auto w-full px-6 py-8 pb-24">

  <!-- Back -->
  <a href="/news/" class="inline-flex items-center gap-1 text-primary font-semibold text-sm mb-6 hover:gap-2 transition-all">
    <span class="material-symbols-outlined text-base">arrow_back</span>
    返回新闻列表
  </a>

  <!-- Article Header -->
  <header class="mb-8">
    <div class="flex items-center gap-3 mb-4">
      <span class="inline-flex items-center px-2.5 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-wider">
        ${post.category === 'case' ? '客户案例' : '新闻资讯'}
      </span>
      <time class="text-sm text-slate-500 dark:text-slate-400 font-medium">
        发布于 ${(post.published_at || '').slice(0, 10)}
      </time>
    </div>
    <h1 class="text-3xl md:text-4xl font-black leading-tight">${post.title}</h1>
  </header>

  <!-- Article Body -->
  <article class="article-body text-lg text-slate-700 dark:text-slate-300 leading-relaxed">
  ${bodyHtml}
  </article>

  <!-- Share & Actions -->
  <div class="mt-10 pt-6 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between">
    <a href="/news/" class="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary text-white font-semibold text-sm hover:bg-primary/90 transition-colors shadow-sm">
      <span class="material-symbols-outlined text-base">arrow_back</span>
      返回新闻列表
    </a>
    <button class="inline-flex items-center gap-2 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 font-medium text-sm hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
      <span class="material-symbols-outlined text-base">share</span>
      分享
    </button>
  </div>

</main>

<footer data-component="footer"
  data-variant="tablet"
  data-active="news">
</footer>

<script defer src="/assets/js/nav-config.js?v=20260415"></script>
    <script defer src="/assets/js/ui/navigator.js?v=20260322-v3"></script>
<script defer src="/assets/js/ui/footer.js?v=20260322-v3"></script>
<script defer src="/assets/js/lang-registry.js"></script>
<script defer src="/assets/js/translations.js"></script>
<script defer src="/assets/js/translations-dropdown-template.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    if (window.translationManager) window.translationManager.initialize();
  });
</script>

<script src="/assets/js/utils/device-utils.js"></script>
<script src="/assets/js/spa-router.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    if (window.SpaRouter && typeof window.SpaRouter.init === 'function') {
      window.SpaRouter.init();
    }
  });
</script>
</body>
</html>`;
  }

  function detailMobileHtml(post) {
    const bodyHtml = mdToHtml(post.content_markdown);
    const escTitle = (post.title || '').replace(/"/g, '&quot;');
    const escExcerpt = (post.excerpt || '').replace(/"/g, '&quot;');
    return `<!DOCTYPE html>
<html class="light" lang="zh-CN">
<head>
<meta charset="utf-8"/>
<link rel="canonical" href="/news/${post.slug}/" />
<meta name="description" content="${escExcerpt || escTitle}">
<meta property="og:type" content="article">
<meta property="og:title" content="YuKoLi 智能厨具 | ${escTitle}">
<meta property="og:description" content="${escExcerpt || escTitle}">
<meta property="og:url" content="https://www.kitchen.yukoli.com/news/${post.slug}/">
<meta property="og:image" content="https://www.kitchen.yukoli.com/assets/images/og-home.webp">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>YuKoLi 智能厨具 | ${escTitle}</title>
<link rel="preload" href="/assets/fonts/local-fonts.css" as="style">
<link rel="preload" href="/assets/css/styles.css" as="style">
<link rel="preload" href="/assets/css/tailwind.css" as="style">
<link rel="preload" href="/assets/fonts/public-sans-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/public-sans-latin-700-normal.woff2" as="font" type="font/woff2" crossorigin>
<link href="/assets/fonts/local-fonts.css" rel="stylesheet"/>
<link rel="stylesheet" href="/assets/css/styles.css">
<link rel="stylesheet" href="/assets/css/tailwind.css">
<link rel="stylesheet" href="/assets/css/z-index-system.css">
<link rel="stylesheet" href="/assets/css/performance-optimizations.css"/>
<style>
  body { min-height: 100dvh; }
  .article-body p { margin-bottom: 1em; line-height: 1.75; }
</style>
<!-- Dark mode: apply saved preference before first paint (prevents flash) -->
<script>(function(){if(localStorage.getItem('darkMode')==='true')document.documentElement.classList.add('dark')})()</script>
<link rel="stylesheet" href="/assets/css/skeleton.css"/>
<link rel="icon" href="/assets/images/logo_header.webp" type="image/webp">
</head>
<body class="bg-background-light dark:bg-background-dark font-display text-slate-900 dark:text-slate-100 antialiased overflow-x-hidden">
<navigator data-component="navigator"
  data-variant="mobile"
  data-active="news">
</navigator>

<div class="relative flex min-h-screen flex-col overflow-x-hidden max-w-md mx-auto shadow-2xl bg-background-light dark:bg-background-dark pb-24">

<main id="spa-content" class="flex-1 px-5 py-6">

  <!-- Back -->
  <a href="/news/" class="inline-flex items-center gap-1 text-primary font-semibold text-sm mb-5">
    <span class="material-symbols-outlined text-base">arrow_back</span>
    返回新闻列表
  </a>

  <!-- Article Header -->
  <header class="mb-6">
    <div class="flex items-center gap-2 mb-3">
      <span class="inline-flex items-center px-2 py-0.5 rounded-full bg-primary/10 text-primary text-[10px] font-bold uppercase tracking-wider">
        ${post.category === 'case' ? '客户案例' : '新闻资讯'}
      </span>
      <time class="text-xs text-slate-500 dark:text-slate-400 font-medium">
        发布于 ${(post.published_at || '').slice(0, 10)}
      </time>
    </div>
    <h1 class="text-2xl font-black leading-tight">${post.title}</h1>
  </header>

  <!-- Article Body -->
  <article class="article-body text-base text-slate-700 dark:text-slate-300">
  ${bodyHtml}
  </article>

  <!-- Actions -->
  <div class="mt-8 pt-6 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between">
    <a href="/news/" class="inline-flex items-center gap-1.5 text-primary font-semibold text-sm">
      <span class="material-symbols-outlined text-base">arrow_back</span>
      返回新闻列表
    </a>
    <button class="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 text-xs font-medium">
      <span class="material-symbols-outlined text-sm">share</span>
      分享
    </button>
  </div>

</main>

<footer data-component="footer"
  data-variant="mobile"
  data-active="news">
</footer>

<script src="/assets/js/utils/device-utils.js"></script>
<script src="/assets/js/spa-router.js"></script>
<script defer src="/assets/js/lang-registry.js"></script>
<script defer src="/assets/js/translations.js"></script>
<script defer src="/assets/js/translations-dropdown-template.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    if (window.translationManager) window.translationManager.initialize();
  });
</script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    if (window.SpaRouter && typeof window.SpaRouter.init === 'function') {
      window.SpaRouter.init();
    }
  });
</script>
</body>
</html>`;
  }

  // ── Index page templates (replace hardcoded articles with dynamic rendering) ──
  function indexPcHtml() {
    const ts = Date.now();
    return `<!DOCTYPE html>
<html class="light" lang="zh-CN">
<head>
<meta charset="utf-8"/>
<link rel="canonical" href="/news/" />
<meta name="description" content="YuKoLi 新闻资讯 — 了解商用厨房自动化最新动态、智能厨具行业趋势与东南亚市场资讯。">
<meta property="og:type" content="website">
<meta property="og:title" content="YuKoLi 智能厨具 | 新闻资讯">
<meta property="og:description" content="YuKoLi 新闻资讯 — 商用厨房自动化最新动态、智能厨具行业趋势与东南亚市场资讯。">
<meta property="og:url" content="https://www.kitchen.yukoli.com/news/">
<meta property="og:image" content="https://www.kitchen.yukoli.com/assets/images/og-home.webp">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>YuKoLi 智能厨具 | 新闻资讯</title>
<link rel="preload" href="/assets/fonts/local-fonts.css" as="style">
<link rel="preload" href="/assets/css/styles.css" as="style">
<link rel="preload" href="/assets/css/tailwind.css" as="style">
<link rel="preload" href="/assets/fonts/public-sans-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/public-sans-latin-700-normal.woff2" as="font" type="font/woff2" crossorigin>
<link href="/assets/fonts/local-fonts.css" rel="stylesheet"/>
<link rel="stylesheet" href="/assets/css/styles.css">
<link rel="stylesheet" href="/assets/css/tailwind.css">
<link rel="stylesheet" href="/assets/css/z-index-system.css">
<link rel="stylesheet" href="/assets/css/performance-optimizations.css"/>
<style>
  body { font-family: 'Public Sans', sans-serif; }
</style>
<!-- Dark mode: apply saved preference before first paint (prevents flash) -->
<script>(function(){if(localStorage.getItem('darkMode')==='true')document.documentElement.classList.add('dark')})()</script>
<link rel="stylesheet" href="/assets/css/skeleton.css"/>
<link rel="icon" href="/assets/images/logo_header.webp" type="image/webp">
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  "name": "YuKoLi 智能厨具 | 新闻资讯",
  "description": "YuKoLi 新闻资讯 — 了解商用厨房自动化最新动态、智能厨具行业趋势。",
  "url": "https://www.kitchen.yukoli.com/news/",
  "isPartOf": {
    "@type": "WebSite",
    "name": "YuKoLi 智能厨具",
    "url": "https://www.kitchen.yukoli.com"
  }
}
</script>
</head>
<body class="bg-background-light dark:bg-background-dark text-slate-900 dark:text-slate-100 antialiased overflow-x-hidden">
<div class="relative flex h-auto min-h-screen w-full flex-col">

<!-- Top Navigation Bar -->
<navigator data-component="navigator"
  data-variant="pc"
  data-active="news"
  data-cta-text-key="nav_get_quote"
  data-cta-href="/quote"></navigator>

<main id="spa-content">

<!-- Hero Section -->
<section class="min-h-[60vh] flex items-center py-16 md:py-24">
<div class="px-6 md:px-10 lg:px-16 xl:px-20 max-w-5xl w-full">
  <div class="flex flex-col gap-4 items-center text-center">
    <span class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-widest">
      <span class="material-symbols-outlined text-xs leading-none">newspaper</span>
      新闻资讯
    </span>
    <h1 class="text-6xl xl:text-8xl font-black leading-[1.1] tracking-tight text-slate-900 dark:text-white">新闻资讯</h1>
    <p class="text-lg xl:text-xl text-slate-600 dark:text-slate-400 max-w-2xl leading-relaxed">了解商用厨房自动化最新动态</p>
  </div>
</div>
</section>

<!-- News List Section -->
<section class="pb-24">
<div class="px-6 md:px-10 lg:px-16 xl:px-20 max-w-5xl">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    <div id="news-grid">
      <!-- Dynamically rendered by post-list.js -->
    </div>
  </div>
</div>
</section>

</main>

</div>

    <script src="/assets/js/ui/dropdown-styles.js"></script>
<script defer src="/assets/js/ui/products-dropdown.js?v=20260322-v3"></script>
<script defer src="/assets/js/nav-config.js?v=20260415"></script>
    <script defer src="/assets/js/ui/navigator.js?v=20260322-v3"></script>
<script defer src="/assets/js/ui/search-engine.js"></script>
<script defer src="/assets/js/ui/footer.js?v=20260322-v3"></script>
<script defer src="/assets/js/lang-registry.js"></script>
<script defer src="/assets/js/translations.js"></script>
<script defer src="/assets/js/translations-dropdown-template.js"></script>
<script defer src="/assets/js/contacts.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    if (window.translationManager) window.translationManager.initialize();
  });
</script>

<script src="/assets/js/utils/device-utils.js"></script>
<script src="/assets/js/spa-router.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    if (window.SpaRouter && typeof window.SpaRouter.init === 'function') {
      window.SpaRouter.init();
    }
  });
</script>
<script defer src="/assets/js/post-list.js?v=${ts}"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var grid = document.getElementById('news-grid');
  if (!grid || !window.POST_LIST) return;
  var parent = grid.parentElement;
  grid.remove();
  window.POST_LIST.forEach(function(post) {
    var article = document.createElement('article');
    article.className = 'group md:col-span-2 lg:col-span-1 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden bg-white dark:bg-slate-900 shadow-sm hover:shadow-lg transition-shadow';
    article.innerHTML =
      (post.cover_image ? '<div class="aspect-video overflow-hidden"><img loading="lazy" alt="' + (post.title||'').replace(/"/g,'&quot;') + '" class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" src="' + post.cover_image + '"></div>' : '') +
      '<div class="p-6">' +
      '<div class="flex items-center gap-2 mb-2">' +
      '<span class="text-xs font-medium px-2 py-0.5 rounded-full bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400">' + (post.category === 'case' ? '客户案例' : '新闻资讯') + '</span>' +
      '<time class="text-xs text-slate-500">' + (post.published_at || '').slice(0, 10) + '</time></div>' +
      '<h3 class="text-lg font-bold mb-2 text-slate-900 dark:text-white line-clamp-2">' + (post.title||'') + '</h3>' +
      (post.excerpt ? '<p class="text-sm text-slate-600 dark:text-slate-400 line-clamp-3">' + post.excerpt + '</p>' : '') +
      '<a href="/news/' + post.slug + '/" class="inline-flex items-center gap-1 mt-3 text-sm font-medium text-indigo-600 dark:text-indigo-400 hover:text-indigo-800">阅读更多 <span class="material-symbols-outlined" style="font-size:1rem">arrow_forward</span></a>' +
      '</div>';
    parent.appendChild(article);
  });
});
</script>
</body>
</html>`;
  }

  function indexTabletHtml() {
    const ts = Date.now();
    return `<!DOCTYPE html>
<html class="light" lang="zh-CN">
<head>
<meta charset="utf-8"/>
<link rel="canonical" href="/news/" />
<meta name="description" content="YuKoLi 新闻资讯 — 了解商用厨房自动化最新动态、智能厨具行业趋势与东南亚市场资讯。">
<meta property="og:type" content="website">
<meta property="og:title" content="YuKoLi 智能厨具 | 新闻资讯">
<meta property="og:description" content="YuKoLi 新闻资讯 — 商用厨房自动化最新动态、智能厨具行业趋势与东南亚市场资讯。">
<meta property="og:url" content="https://www.kitchen.yukoli.com/news/">
<meta property="og:image" content="https://www.kitchen.yukoli.com/assets/images/og-home.webp">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>YuKoLi 智能厨具 | 新闻资讯</title>
<link rel="preload" href="/assets/fonts/local-fonts.css" as="style">
<link rel="preload" href="/assets/css/styles.css" as="style">
<link rel="preload" href="/assets/css/tailwind.css" as="style">
<link rel="preload" href="/assets/fonts/public-sans-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/public-sans-latin-700-normal.woff2" as="font" type="font/woff2" crossorigin>
<link href="/assets/fonts/local-fonts.css" rel="stylesheet"/>
<link rel="stylesheet" href="/assets/css/styles.css">
<link rel="stylesheet" href="/assets/css/tailwind.css">
<link rel="stylesheet" href="/assets/css/z-index-system.css">
<link rel="stylesheet" href="/assets/css/performance-optimizations.css"/>
<!-- Dark mode: apply saved preference before first paint (prevents flash) -->
<script>(function(){if(localStorage.getItem('darkMode')==='true')document.documentElement.classList.add('dark')})()</script>
<link rel="stylesheet" href="/assets/css/skeleton.css"/>
<link rel="icon" href="/assets/images/logo_header.webp" type="image/webp">
</head>
<body class="bg-background-light dark:bg-background-dark font-display text-slate-900 dark:text-slate-100 antialiased overflow-x-hidden">
<div class="relative flex min-h-screen flex-col">

<!-- ═══ Max Display Header (Tablet) ═══ -->
<navigator data-component="navigator"
  data-variant="tablet"
  data-search="true"
  data-active="news"
  data-cta-text-key="nav_get_quote"
  data-cta-href="/quote"></navigator>

<!-- ─── Main Content ─────────────────────────────────────────────────────── -->
<main id="spa-content" class="flex-1 max-w-4xl mx-auto w-full py-8 pb-24">

  <!-- Hero Section -->
  <div class="relative overflow-hidden rounded-2xl bg-slate-900 aspect-[21/9] flex items-end mb-8"
       style="background-image: linear-gradient(to top, rgba(34,22,16,0.9), rgba(34,22,16,0)); background-size: cover; background-position: center;">
    <div class="p-8 w-full">
      <span class="inline-block px-2 py-1 mb-3 rounded bg-primary text-white text-xs font-bold uppercase tracking-wider">新闻资讯</span>
      <h2 class="text-white text-4xl font-bold leading-tight">新闻资讯</h2>
      <p class="text-slate-300 text-base mt-2">了解商用厨房自动化最新动态</p>
    </div>
  </div>

  <!-- News List -->
  <div id="news-list" class="flex flex-col gap-6">
    <!-- Dynamically rendered by post-list.js -->
  </div>

</main>

<footer data-component="footer"
  data-variant="tablet"
  data-active="news">
</footer>

<script defer src="/assets/js/nav-config.js?v=20260415"></script>
    <script defer src="/assets/js/ui/navigator.js?v=20260322-v3"></script>
<script defer src="/assets/js/ui/footer.js?v=20260322-v3"></script>
<script defer src="/assets/js/lang-registry.js"></script>
<script defer src="/assets/js/translations.js"></script>
<script defer src="/assets/js/translations-dropdown-template.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    if (window.translationManager) window.translationManager.initialize();
  });
</script>

<script src="/assets/js/utils/device-utils.js"></script>
<script src="/assets/js/spa-router.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    if (window.SpaRouter && typeof window.SpaRouter.init === 'function') {
      window.SpaRouter.init();
    }
  });
</script>
<script defer src="/assets/js/post-list.js?v=${ts}"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var list = document.getElementById('news-list');
  if (!list || !window.POST_LIST) return;
  list.innerHTML = window.POST_LIST.map(function(post) {
    return '<article class="group rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden bg-white dark:bg-slate-900 shadow-sm hover:shadow-lg transition-shadow">' +
      (post.cover_image ? '<div class="aspect-[21/9] overflow-hidden"><img loading="lazy" alt="' + (post.title||'').replace(/"/g,'&quot;') + '" class="w-full h-full object-cover" src="' + post.cover_image + '"></div>' : '') +
      '<div class="p-6 flex flex-col gap-3">' +
      '<time class="text-sm text-slate-500 dark:text-slate-400 font-medium">' + (post.published_at || '').slice(0, 10) + '</time>' +
      '<h3 class="text-lg font-bold leading-snug group-hover:text-primary transition-colors">' + (post.title||'') + '</h3>' +
      (post.excerpt ? '<p class="text-sm text-slate-600 dark:text-slate-400 line-clamp-3">' + post.excerpt + '</p>' : '') +
      '<a href="/news/' + post.slug + '/" class="inline-flex items-center gap-1 text-primary font-semibold text-sm mt-2 hover:gap-2 transition-all">阅读更多 <span class="material-symbols-outlined text-base">arrow_forward</span></a>' +
      '</div></article>';
  }).join('');
});
</script>
</body>
</html>`;
  }

  function indexMobileHtml() {
    const ts = Date.now();
    return `<!DOCTYPE html>
<html class="light" lang="zh-CN">
<head>
<meta charset="utf-8"/>
<link rel="canonical" href="/news/" />
<meta name="description" content="YuKoLi 新闻资讯 — 了解商用厨房自动化最新动态、智能厨具行业趋势与东南亚市场资讯。">
<meta property="og:type" content="website">
<meta property="og:title" content="YuKoLi 智能厨具 | 新闻资讯">
<meta property="og:description" content="YuKoLi 新闻资讯 — 商用厨房自动化最新动态、智能厨具行业趋势与东南亚市场资讯。">
<meta property="og:url" content="https://www.kitchen.yukoli.com/news/">
<meta property="og:image" content="https://www.kitchen.yukoli.com/assets/images/og-home.webp">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>YuKoLi 智能厨具 | 新闻资讯</title>
<link rel="preload" href="/assets/fonts/local-fonts.css" as="style">
<link rel="preload" href="/assets/css/styles.css" as="style">
<link rel="preload" href="/assets/css/tailwind.css" as="style">
<link rel="preload" href="/assets/fonts/public-sans-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/public-sans-latin-700-normal.woff2" as="font" type="font/woff2" crossorigin>
<link href="/assets/fonts/local-fonts.css" rel="stylesheet"/>
<link rel="stylesheet" href="/assets/css/styles.css">
<link rel="stylesheet" href="/assets/css/tailwind.css">
<link rel="stylesheet" href="/assets/css/z-index-system.css">
<link rel="stylesheet" href="/assets/css/performance-optimizations.css"/>
<style>
  body {
    min-height: 100dvh;
  }
</style>
<!-- Dark mode: apply saved preference before first paint (prevents flash) -->
<script>(function(){if(localStorage.getItem('darkMode')==='true')document.documentElement.classList.add('dark')})()</script>
<link rel="stylesheet" href="/assets/css/skeleton.css"/>
<link rel="icon" href="/assets/images/logo_header.webp" type="image/webp">
</head>
<body class="bg-background-light dark:bg-background-dark font-display text-slate-900 dark:text-slate-100 antialiased overflow-x-hidden">
<navigator data-component="navigator"
  data-variant="mobile"
  data-active="news">
</navigator>

<div class="relative flex min-h-screen flex-col overflow-x-hidden max-w-md mx-auto shadow-2xl bg-background-light dark:bg-background-dark pb-24">

<main id="spa-content" class="flex-1 px-5 py-6">

  <!-- Hero Section -->
  <div class="mb-8">
    <h1 class="text-3xl font-black leading-tight">新闻资讯</h1>
    <p class="text-base text-slate-600 dark:text-slate-400 mt-2">了解商用厨房自动化最新动态</p>
  </div>

  <!-- News List -->
  <div id="news-list" class="flex flex-col gap-5">
    <!-- Dynamically rendered by post-list.js -->
  </div>

</main>

<footer data-component="footer"
  data-variant="mobile"
  data-active="news">
</footer>

<script src="/assets/js/utils/device-utils.js"></script>
<script src="/assets/js/spa-router.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    if (window.SpaRouter && typeof window.SpaRouter.init === 'function') {
      window.SpaRouter.init();
    }
  });
</script>
<script defer src="/assets/js/post-list.js?v=${ts}"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var list = document.getElementById('news-list');
  if (!list || !window.POST_LIST) return;
  list.innerHTML = window.POST_LIST.map(function(post) {
    return '<article class="group rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden bg-white dark:bg-slate-900 shadow-sm">' +
      (post.cover_image ? '<div class="aspect-[16/9] overflow-hidden"><img loading="lazy" alt="' + (post.title||'').replace(/"/g,'&quot;') + '" class="w-full h-full object-cover" src="' + post.cover_image + '"></div>' : '') +
      '<div class="p-5 flex flex-col gap-2">' +
      '<time class="text-xs text-slate-500 dark:text-slate-400 font-medium">' + (post.published_at || '').slice(0, 10) + '</time>' +
      '<h3 class="text-base font-bold leading-snug">' + (post.title||'') + '</h3>' +
      (post.excerpt ? '<p class="text-sm text-slate-600 dark:text-slate-400 line-clamp-2">' + post.excerpt + '</p>' : '') +
      '<a href="/news/' + post.slug + '/" class="inline-flex items-center gap-1 text-primary font-semibold text-sm mt-1">阅读更多 <span class="material-symbols-outlined text-base">arrow_forward</span></a>' +
      '</div></article>';
  }).join('');
});
</script>
</body>
</html>`;
  }

  // POST /publish/posts — SSG: 生成新闻详情页 + 列表页
  router.post('/publish/posts', requireAdmin, (req, res) => {
    try {
      const projectRoot = path.join(__dirname, '..', '..', '..');
      const newsDir = path.join(projectRoot, 'src', 'pages', 'news');
      const jsDir = path.join(projectRoot, 'src', 'assets', 'js');

      fs.mkdirSync(newsDir, { recursive: true });
      fs.mkdirSync(jsDir, { recursive: true });

      // 1. Read published posts
      const posts = db.prepare(
        'SELECT id, title, slug, excerpt, cover_image, category, content_markdown, published_at FROM posts WHERE is_active = 1 AND published_at IS NOT NULL ORDER BY published_at DESC'
      ).all();

      // 2. Generate detail pages
      const generators = [
        { suffix: 'pc',     fn: detailPcHtml },
        { suffix: 'tablet', fn: detailTabletHtml },
        { suffix: 'mobile', fn: detailMobileHtml }
      ];

      posts.forEach(post => {
        if (!post.slug) return;
        generators.forEach(({ suffix, fn }) => {
          const filePath = path.join(newsDir, post.slug + '-' + suffix + '.html');
          fs.writeFileSync(filePath, fn(post), 'utf-8');
        });
      });

      // 3. Generate post-list.js
      const listData = posts.map(p => ({
        id: p.id,
        title: p.title,
        slug: p.slug,
        excerpt: p.excerpt,
        cover_image: p.cover_image,
        category: p.category,
        published_at: p.published_at
      }));

      const listOutput = '// post-list.js — Auto-generated by CMS (' + new Date().toISOString() + ')\n// DO NOT EDIT MANUALLY\n\n(function() {\n  var posts = ' + JSON.stringify(listData, null, 2) + ';\n  window.POST_LIST = posts;\n})();\n';
      fs.writeFileSync(path.join(jsDir, 'post-list.js'), listOutput, 'utf-8');

      // 4. Generate index pages
      fs.writeFileSync(path.join(newsDir, 'index-pc.html'), indexPcHtml(), 'utf-8');
      fs.writeFileSync(path.join(newsDir, 'index-tablet.html'), indexTabletHtml(), 'utf-8');
      fs.writeFileSync(path.join(newsDir, 'index-mobile.html'), indexMobileHtml(), 'utf-8');

      logAudit(db, req.user.userId, req.user.username, 'publish', 'posts', null, null, {
        posts: posts.length,
        detailPages: posts.length * 3,
        indexPages: 3
      });

      res.json({
        message: 'Published posts successfully',
        stats: {
          posts: posts.length,
          detailPages: posts.length * 3,
          indexPages: 3,
          postListJs: true
        }
      });
    } catch (e) {
      res.status(500).json({ error: e.message });
    }
  });

  // POST /publish/deploy — 一键发布到网站（生成数据 + 同步图片 + git push）
  router.post('/deploy', requireAdmin, (req, res) => {
    try {
      const { execSync } = require('child_process');
      const projectRoot = path.join(__dirname, '..', '..', '..');

      // 1. 同步图片：把 CMS 上传的图片复制到网站资源目录
      const srcUploads = path.join(__dirname, '..', 'uploads');
      const dstImages = path.join(projectRoot, 'src', 'assets', 'images', 'products');
      if (fs.existsSync(srcUploads)) {
        fs.mkdirSync(dstImages, { recursive: true });
        const files = fs.readdirSync(srcUploads);
        let copied = 0;
        files.forEach(f => {
          const src = path.join(srcUploads, f);
          const dst = path.join(dstImages, f);
          if (fs.statSync(src).isFile() && !fs.existsSync(dst)) {
            fs.copyFileSync(src, dst);
            copied++;
          }
        });
        console.log('[CMS] Copied', copied, 'images to', dstImages);
      }

      // 2. Git add + commit + push
      const addCmd = `cd "${projectRoot}" && git add src/assets/js/product-data-table.js src/assets/images/products/ 2>/dev/null; echo "done"`;
      execSync(addCmd, { stdio: 'pipe' });

      const commitCmd = `cd "${projectRoot}" && git commit -m "cms: auto-publish ${new Date().toISOString().slice(0,16)}" --allow-empty`;
      try { execSync(commitCmd, { stdio: 'pipe' }); } catch(e) { /* nothing to commit is ok */ }

      const pushCmd = `cd "${projectRoot}" && git push origin dev`;
      execSync(pushCmd, { stdio: 'pipe', timeout: 30000 });

      logAudit(db, req.user.userId, req.user.username, 'deploy', 'cms', null, null, { status: 'pushed' });
      res.json({ message: '发布成功，预计 2-5 分钟内网站更新', status: 'pushed' });
    } catch (e) {
      logAudit(db, req.user.userId, req.user.username, 'deploy', 'cms', null, null, { status: 'error', error: e.message });
      res.status(500).json({ error: '发布失败: ' + e.message });
    }
  });

  return router;
}

module.exports = { publishRoutes };
