'use strict';

// Static site generation for news pages.
// Generates detail pages (pc/tablet/mobile) and index pages.

const path = require('path');
const fs = require('fs');
const { logAudit } = require('../../db/init');
const {
  detailPcHtml,
  detailTabletHtml,
  detailMobileHtml,
  indexPcHtml,
  indexTabletHtml,
  indexMobileHtml
} = require('./templates');

function ssgRoutes(db) {
  const express = require('express');
  const router = express.Router();
  const { requireAdmin } = require('../auth');

  // POST /publish/posts — SSG: 生成新闻详情页 + 列表页
  router.post('/publish/posts', requireAdmin, (req, res) => {
    try {
      const projectRoot = path.join(__dirname, '..', '..', '..', '..');
      const newsDir = path.join(projectRoot, 'src', 'pages', 'news');
      const jsDir = path.join(projectRoot, 'src', 'assets', 'js');

      fs.mkdirSync(newsDir, { recursive: true });
      fs.mkdirSync(jsDir, { recursive: true });

      // 1. Read published posts
      const posts = db.prepare(
        'SELECT id, title, slug, excerpt, cover_image, category, content_markdown, published_at FROM posts WHERE is_active = 1 AND published_at IS NOT NULL ORDER BY published_at DESC'
      ).all();

      // 2. Generate detail pages
      const generators = [
        { suffix: 'pc',     fn: detailPcHtml },
        { suffix: 'tablet', fn: detailTabletHtml },
        { suffix: 'mobile', fn: detailMobileHtml }
      ];

      posts.forEach(post => {
        if (!post.slug) return;
        generators.forEach(({ suffix, fn }) => {
          const filePath = path.join(newsDir, post.slug + '-' + suffix + '.html');
          fs.writeFileSync(filePath, fn(post), 'utf-8');
        });
      });

      // 3. Generate post-list.js
      const listData = posts.map(p => ({
        id: p.id,
        title: p.title,
        slug: p.slug,
        excerpt: p.excerpt,
        cover_image: p.cover_image,
        category: p.category,
        published_at: p.published_at
      }));

      const listOutput = '// post-list.js — Auto-generated by CMS (' + new Date().toISOString() + ')\n// DO NOT EDIT MANUALLY\n\n(function() {\n  var posts = ' + JSON.stringify(listData, null, 2) + ';\n  window.POST_LIST = posts;\n})();\n';
      fs.writeFileSync(path.join(jsDir, 'post-list.js'), listOutput, 'utf-8');

      // 4. Generate index pages
      fs.writeFileSync(path.join(newsDir, 'index-pc.html'), indexPcHtml(), 'utf-8');
      fs.writeFileSync(path.join(newsDir, 'index-tablet.html'), indexTabletHtml(), 'utf-8');
      fs.writeFileSync(path.join(newsDir, 'index-mobile.html'), indexMobileHtml(), 'utf-8');

      logAudit(db, req.user.userId, req.user.username, 'publish', 'posts', null, null, {
        posts: posts.length,
        detailPages: posts.length * 3,
        indexPages: 3
      });

      res.json({
        message: 'Published posts successfully',
        stats: {
          posts: posts.length,
          detailPages: posts.length * 3,
          indexPages: 3,
          postListJs: true
        }
      });
    } catch (e) {
      res.status(500).json({ error: e.message });
    }
  });

  return router;
}

module.exports = { ssgRoutes };
