#!/usr/bin/env node
'use strict';

/**
 * CMS Publish Script
 * Reads from cms.db and generates src/assets/js/product-data-table.js
 * Usage: node scripts/cms-publish.js
 */

const path = require('path');
const fs = require('fs');
const Database = require('better-sqlite3');

const DB_PATH = path.join(__dirname, '..', 'src', 'admin', 'data', 'cms.db');
const OUTPUT_PATH = path.join(__dirname, '..', 'src', 'assets', 'js', 'product-data-table.js');

if (!fs.existsSync(DB_PATH)) {
  console.error('❌ cms.db not found at', DB_PATH);
  console.error('   Run the CMS server first to initialize the database.');
  process.exit(1);
}

const db = new Database(DB_PATH, { readonly: true });

const categories = db.prepare(
  'SELECT * FROM product_categories WHERE is_active = 1 ORDER BY sort_order ASC, id ASC'
).all();

const allProducts = db.prepare(
  `SELECT p.*, c.slug as category_slug, c.i18n_key as category_i18n_key
   FROM products p LEFT JOIN product_categories c ON p.category_id = c.id
   WHERE p.is_active = 1 ORDER BY p.sort_order ASC, p.id ASC`
).all();

const allImages = db.prepare(
  'SELECT * FROM product_images ORDER BY sort_order ASC'
).all();

// Group images by product_id
const imgMap = {};
allImages.forEach(img => {
  if (!imgMap[img.product_id]) imgMap[img.product_id] = [];
  imgMap[img.product_id].push(img);
});

// Group products by category
const catMap = {};
allProducts.forEach(p => {
  const catSlug = p.category_slug || 'Uncategorized';
  if (!catMap[catSlug]) {
    catMap[catSlug] = { category: p.category_i18n_key || p.category_slug, products: [] };
  }
  catMap[catSlug].products.push({
    category: p.category_i18n_key || p.category_slug,
    subCategory: p.sub_category || null,
    model: p.model,
    status: p.status,
    is_active: !!p.is_active,
    badge: p.badge || null,
    badgeColor: p.badge_color || null,
    power: p.power || null,
    throughput: p.throughput || null,
    averageTime: p.average_time || null,
    voltage: p.voltage || null,
    frequency: p.frequency || null,
    material: p.material || null,
    productDimensions: p.product_dimensions || null,
    color: p.color || null,
    controlMethod: p.control_method || null,
    launchTime: p.launch_time || null,
    images: (imgMap[p.id] || []).map(i => ({
      filePath: i.file_path,
      isPrimary: !!i.is_primary,
      sortOrder: i.sort_order
    }))
  });
});

// Build output array preserving category order
const table = [];
const addedCats = new Set();

categories.forEach(cat => {
  if (catMap[cat.slug]) {
    table.push(catMap[cat.slug]);
    addedCats.add(cat.slug);
  }
});

Object.keys(catMap).forEach(slug => {
  if (!addedCats.has(slug)) {
    table.push(catMap[slug]);
  }
});

const output = `// product-data-table.js — Auto-generated by CMS (${new Date().toISOString()})\n// DO NOT EDIT MANUALLY — Changes will be overwritten on next publish\n\nexport const PRODUCT_DATA_TABLE = ${JSON.stringify(table, null, 2)};\n`;

fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');

db.close();

console.log('✅ Published successfully!');
console.log(`   Categories: ${categories.length}`);
console.log(`   Products:   ${allProducts.length}`);
console.log(`   Images:     ${allImages.length}`);
console.log(`   Output:     ${OUTPUT_PATH}`);
